services:
  keycloak:
    image: keycloak/keycloak:26.0.7-0
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./docker/keycloak/realm-import.json:/opt/keycloak/data/import/realm-import.json
    environment:
      KC_BOOTSTRAP_ADMIN_USER: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
